### ISSUE TITLE
[FEATURE REQUEST] - Make SD Prompt Reader available as ComfyUI nodes

### ISSUE THREAD

**Issue by karl-von-knecht** [receyuki/stable-diffusion-prompt-reader#27]
Could you make some of this functionality available as a set of comfyUI nodes? This would greatly help people who have switched from automatic1111 to ComfyUI, allowing them to process and refine their existing automatic1111 images with ComfyUI without having to manually specify the prompts every time.

**Comment by receyuki** [comment]
This sounds intriguing and feasible. Could you provide a more detailed description of your workflow and what tasks you need this node to assist you with?

**Comment by csmith14** [comment]
@receyuki Bumping this.

Since this thread hasn't been updated in a bit, I'll just say the custom nodes ecosystem is sorely lacking a node that can extract amount of fields this project is doing.

I believe the idea would be that the node accepts file upload and provides each of the fields currently displayed in the standalone app as individual outputs from the node, presumably as primitives.

**Comment by receyuki** [comment]
@csmith14 Actually, I started developing a node that inherits the SD Prompt Reader's metadata reading functionality a few days ago. I will let you know when I've completed the first version.

**Comment by receyuki** [comment]
@karl-von-knecht @csmith14 
I just released the SD Prompt Reader ComfyUI node version, try it out. If you encounter any issues or have any suggestions, please let me know.
https://github.com/receyuki/comfyui-prompt-reader-node

**Comment by csmith14** [comment]
Thanks @receyuki !

Will definitely check it out in the next couple of days.
