### ISSUE TITLE
[FORMAT SUPPORT] - SwarmUI

### ISSUE THREAD

**Issue by CBook424** [receyuki/stable-diffusion-prompt-reader#37]
### Summary

I would like to be able to know the information about generating images in SwarmUI

### Basic Example

Hopefully SwarmUI will be supported

**Comment by receyuki** [comment]
Absolutely! Thank you for letting me know about this new tool. Since it's an official tool from Stability AI, I'll definitely support the StableSwarmUI format. Currently, StableSwarmUI is still in its Alpha version. I will work on supporting the current format of StableSwarmUI asap. However, no one can guarantee that future versions of StableSwarmUI will not change the image format.

**Comment by receyuki** [comment]
Wait! I just realised that StableSwarmUI writes both its own parameters and the backend parameters into the images. I tried it out just now, and if I use ComfyUI as the backend, the images are correctly processed just like images generated directly by ComfyUI.

**Comment by receyuki** [comment]
https://github.com/receyuki/stable-diffusion-prompt-reader/releases/tag/v1.3.3-beta.2
I just released beta 2. Try it out.
