### ISSUE TITLE
Malware warning.

### ISSUE THREAD

**Issue by ZeroCool22** [receyuki/stable-diffusion-prompt-reader#8]
![Screenshot_1](https://user-images.githubusercontent.com/13344308/235035362-c9252043-b912-4f0c-a491-2d5cb14ea514.png)

**Comment by receyuki** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/13344308/235035362-c9252043-b912-4f0c-a491-2d5cb14ea514.png)

Thank you for your feedback. 
Firstly I need to explain that the false positive is caused by the packaging tool that I use (pyinstaller). I spent a lot of time trying to fix the Windows Defender false positive before, but I couldn't do it for every antivirus software. 
I just checked the Malwarebytes forum and found that many developers using the same packaging tool as me are experiencing the same problem. I could contact Malwarebytes and get them to whitelist SD prompt reader v1.2, but the next version will still encounter the same false positive.
So, you can either trust Windows Defender or use [the instruction for Linux users](https://github.com/receyuki/stable-diffusion-prompt-reader#for-linux-users-not-regularly-tested) to use this program. Thx.
